language: python

python:
  - "3.7"

notifications:
  email:
    on_success: never

install:
  - pip install mkdocs
  - pip install pygments
  - echo -e "machine github.com\n  login ${GITHUB_API_KEY}" > ~/.netrc

script:
  - find docs/ -type f -name "*.txt" -print0 | xargs -0 sed -i 's/\/img\//\/courses-wiki\/img\//g' {};
  # 批量将 txt 都改为 xml 避免 gitee pages 不支持访问
  - find docs/ -type f -name "*.txt" -print0 | xargs -0 rename "s/\.txt/\.xml/g" {};
  - find docs/ -type f -name "*.md" -print0 | xargs -0 sed -i 's/\/img\//\/courses-wiki\/img\//g' {};
  - sed -i 's/\/assets\//\/courses-wiki\/assets\//g' material/slideshow.html
  - for file in $(grep --include=\*.md -rl 'docs/' -e "iframe src=\"\.\/slideshow\.html\"");do name=$(echo $file | cut -d'/' -f 3 | cut -d'.' -f 1);sed -i "s/src=\"\.\/slideshow\.html\"/src=\"\.\/$name\/slideshow\.html\"/g" $file;done
  - mkdocs gh-deploy --force --clean

branches:
  only:
    - master
